import assert from "node:assert/strict";
import {normalizeHealth, healthScore, validMeasurement, isDue, reminderCalendar, localDay, EMPTY_HEALTH} from "../src/lib/wellness";
import {getRecommendations} from "../src/lib/recommendations";
import {matchesDietaryPreference} from "../src/lib/dietary";
import {FOODS} from "../src/data/foods";
import {TERMS,termFor} from "../src/data/glossary";
import {STORAGE_KEYS, clearAllMoodMealData} from "../src/lib/storage";
assert.deepEqual(normalizeHealth(null),EMPTY_HEALTH);
assert.deepEqual(normalizeHealth({conditions:[null,3,"Depression"],notes:9,personalized:"yes"}),{conditions:["Depression"],notes:"",personalized:false});
const anemia={conditions:["Iron-deficiency anemia"],notes:"",personalized:true};
const iron=FOODS.find(f=>f.id==="spinach")!;
assert.ok(healthScore(iron,anemia)>0);
assert.equal(healthScore(iron,{...anemia,personalized:false}),0);
assert.equal(healthScore(iron,{...anemia,conditions:["Anemia (cause unknown)"]}),0);
assert.equal(healthScore(iron,{...anemia,conditions:[...anemia.conditions,"Kidney disease"]}),0);
const base=getRecommendations({emotionId:"happy",intensity:5});
assert.deepEqual(getRecommendations({emotionId:"happy",intensity:5,health:EMPTY_HEALTH}),base);
const tailored=getRecommendations({emotionId:"happy",intensity:5,health:anemia,dietaryPreferences:"vegan"});
assert.ok(tailored.foods.some(f=>f.nutrients.includes("Iron")));
assert.ok(tailored.foods.every(f=>matchesDietaryPreference(f,"vegan")));
assert.ok(tailored.meals.every(f=>matchesDietaryPreference(f,"vegan")));
const weight={id:"a",date:"2020-01-01T09:00:00Z",kind:"weight" as const,value:70,unit:"kg",note:""};
assert.ok(validMeasurement(weight));
assert.ok(!validMeasurement({...weight,value:NaN}));
assert.ok(!validMeasurement({...weight,value:-1}));
assert.ok(!validMeasurement({...weight,date:"not-a-date"}));
assert.ok(!validMeasurement({...weight,date:"2999-01-01"}));
assert.ok(!validMeasurement({...weight,unit:"mmHg"}));
assert.ok(validMeasurement({...weight,kind:"blood-pressure",value:120,second:80,unit:"mmHg"}));
assert.ok(!validMeasurement({...weight,kind:"blood-pressure",value:80,second:120,unit:"mmHg"}));
assert.ok(validMeasurement({...weight,kind:"pulse",value:65,unit:"bpm"}));
const now=new Date(2026,9,5,9,0,0);
const reminder={id:"test",name:"Test, name; safe\nsecond line",kind:"Vitamin" as const,time:"09:00",instructions:"Use prescribed instructions",startDate:"2026-10-05",enabled:true};
assert.ok(isDue(reminder,now));
assert.ok(!isDue(reminder,new Date(2026,9,5,8,59)));
assert.ok(!isDue({...reminder,enabled:false},now));
assert.ok(!isDue({...reminder,startDate:"2026-10-06"},now));
assert.ok(!isDue({...reminder,handledDate:localDay(now)},now));
assert.ok(isDue({...reminder,handledDate:localDay(now)},new Date(2026,9,6,9,0)));
const ics=reminderCalendar(reminder,new Date(2026,9,5,10,0));
assert.ok(ics.includes("DTSTART:20261006T090000"));
assert.ok(ics.includes("RRULE:FREQ=DAILY\r\n"));
assert.ok(ics.includes("SUMMARY:Test\\, name\\; safe\\nsecond line"));
assert.ok(ics.includes("BEGIN:VALARM"));
assert.ok(!ics.includes(".000Z"));
assert.equal(termFor("Complex Carbs")?.id,"carbohydrates");
assert.equal(termFor("Vitamin C")?.id,"vitamin-c");
assert.equal(new Set(TERMS.map(t=>t.id)).size,TERMS.length);
const removed:string[]=[];
(globalThis as any).window={localStorage:{removeItem:(key:string)=>removed.push(key)}};
clearAllMoodMealData();
for(const key of [STORAGE_KEYS.health,STORAGE_KEYS.measurements,STORAGE_KEYS.reminders])assert.ok(removed.includes(key));
console.log("PASS: normalization, ranking/opt-out/renal guard, dietary filters, units, BP/date validation, reminder timing/deduplication/recurrence/calendar escaping, glossary, clear data");

const longCalendar=reminderCalendar({...reminder,instructions:"é".repeat(200)},now);
assert.ok(longCalendar.split("\r\n").every(line=>new TextEncoder().encode(line).length<=75));
