import {useState} from "react";
import {enableReminderSound} from "../lib/reminderSound";
import Header from "../components/Header";
import {useReminders} from "../hooks/useWellness";
import {localDay,reminderCalendar,downloadFile,type Reminder} from "../lib/wellness";
export default function RemindersPage(){
 const [items,save]=useReminders();const [editing,setEditing]=useState<string|null>(null);const [name,setName]=useState("");const [kind,setKind]=useState<Reminder["kind"]>("Medicine");const [time,setTime]=useState("09:00");const [startDate,setStart]=useState(localDay);const [instructions,setInstructions]=useState("");const [message,setMessage]=useState("");
 const reset=()=>{setEditing(null);setName("");setInstructions("");};
 return <div className="mm-soft-bg flex h-full flex-1 flex-col"><Header title="Medicine & vitamin reminders"/><div className="screen-scroll space-y-4 px-4 pt-4">
 <div className="card text-sm"><p>Daily reminders use this device’s local time. Add a separate reminder for each daily dose time.</p><p className="mt-2 font-semibold">In-app alerts work only while MoodMeal is open and the device is awake. For alarms with the app closed, export to your calendar and verify its notification settings.</p><p className="mt-2 text-xs">Follow your prescriber’s timing and instructions. A missed alert is not advice to take or double a dose. Exported calendar entries may sync to your calendar provider; editing or deleting here does not update them.</p></div>
 <button className="well-secondary" onClick={async()=>{try{await enableReminderSound();setMessage("Sound enabled for this open session. Keep the device awake and volume on.");}catch{setMessage("Sound is unavailable. Use calendar alarms instead.");}}}>Enable and test reminder sound</button>
 <form className="card space-y-3" onSubmit={e=>{e.preventDefault();if(!name.trim())return;const old=items.find(r=>r.id===editing);const r:Reminder={id:editing??crypto.randomUUID(),name:name.trim(),kind,time,startDate,instructions:instructions.trim(),enabled:old?.enabled??true,handledDate:old?.time===time?old.handledDate:undefined};if(!save(editing?items.map(x=>x.id===editing?r:x):[...items,r]))return;reset();setMessage("Reminder saved. Keep the app open or export a calendar alarm.");}}>
 <h2 className="section-title">{editing?"Edit reminder":"New daily reminder"}</h2><label className="block">Name<input className="well-input" required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Medicine or vitamin name"/></label>
 <label className="block">Type<select className="well-input" value={kind} onChange={(e: {target: {value: string}})=>setKind(e.target.value as Reminder["kind"])}><option>Medicine</option><option>Vitamin</option></select></label>
 <label className="block">Time<input className="well-input" type="time" required value={time} onInput={e=>setTime(e.currentTarget.value)} onChange={e=>setTime(e.target.value)}/></label><label className="block">Start date<input className="well-input" type="date" required value={startDate} onInput={e=>setStart(e.currentTarget.value)} onChange={e=>setStart(e.target.value)}/></label>
 <label className="block">Your prescribed instructions (optional)<textarea className="well-input" maxLength={500} value={instructions} onChange={e=>setInstructions(e.target.value)} /></label>
 <button className="well-primary" type="submit">Save reminder</button>{editing&&<button className="well-secondary" type="button" onClick={reset}>Cancel edit</button>}<p role="status">{message}</p></form>
 {!items.length&&<p>No reminders yet.</p>}{items.map(r=><article className="card space-y-2" key={r.id}><h2 className="font-bold">{r.name}</h2><p className="text-sm">{r.kind} · Daily at {r.time} · {r.enabled?"Active":"Paused"}</p><p className="text-xs">Starts {r.startDate} · {r.instructions}</p><div className="flex flex-wrap gap-2"><button className="well-secondary" onClick={()=>{setEditing(r.id);setName(r.name);setKind(r.kind);setTime(r.time);setStart(r.startDate);setInstructions(r.instructions);}}>Edit</button><button className="well-secondary" onClick={()=>save(items.map(x=>x.id===r.id?{...x,enabled:!x.enabled}:x))}>{r.enabled?"Pause":"Resume"}</button><button className="well-secondary" onClick={()=>downloadFile("moodmeal-reminder.ics",reminderCalendar(r),"text/calendar")}>Export calendar alarm</button><button className="well-secondary" onClick={()=>{save(items.filter(x=>x.id!==r.id));if(editing===r.id)reset();}}>Delete reminder</button></div></article>)}
 </div></div>;
}
