import Header from "../components/Header";
import {useHealth} from "../hooks/useWellness";
import {useDraftMood} from "../hooks/useDraftMood";
import {Link} from "../lib/router";
export default function SelfCarePage(){
 const [health]=useHealth();const {draft}=useDraftMood();const low=health.conditions.includes("Depression") || draft?.emotionId === "sad";const stress=health.conditions.includes("Anxiety") || ["nervous","worried","angry"].includes(draft?.emotionId ?? "");
 const practices=[
 {title:"A gentle check-in",why:low?"For low mood: start with one manageable action.":"Make space for how you feel today.",steps:"Choose one small task, such as opening the curtains or messaging someone you trust. It is okay to start small.",source:"https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health",rank:low?3:0},
 {title:"Grounding or meditation",why:stress?"For stress or worry: take a short pause.":"A brief moment to notice the present.",steps:"For 1–3 minutes, notice your feet on the floor and the sounds around you. Let breathing stay natural. Keep your eyes open if that feels better; stop if you feel distressed or dizzy.",source:"https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety",rank:stress?3:0},
 {title:"Gentle yoga or chair movement",why:"An adaptable way to explore movement and relaxation.",steps:"Try comfortable shoulder rolls or easy seated stretches for a few minutes. Avoid painful positions, breath holding and hot yoga. Ask your clinician about modifications if you have a health condition or are pregnant.",source:"https://www.nccih.nih.gov/health/yoga-effectiveness-and-safety",rank:0},
 {title:"An easy walk or seated movement",why:health.conditions.includes("Hypertension")?"A movement routine to discuss alongside your blood pressure care plan.":"A little movement can be part of a steady routine.",steps:"If appropriate for you, choose a comfortable pace for a short walk or seated movement. Build gradually. Stop if you feel unwell; follow any exercise limits from your care team.",source:"https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health",rank:health.conditions.includes("Hypertension")?2:0},
 {title:"A consistent wind-down",why:"Support a regular sleep routine.",steps:"Pick a repeatable bedtime routine: dim the lights, set aside screens and do something calming. Aim for a schedule you can maintain.",source:"https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health",rank:0},
 ].sort((a,b)=>b.rank-a.rank);
 return <div className="mm-soft-bg flex h-full flex-1 flex-col"><Header title="Self-care for you" /><div className="screen-scroll space-y-4 px-4 pt-4"><p className="text-sm">Suggestions reflect your saved conditions and latest mood check-in. Choose what feels manageable; these practices complement professional care.</p><Link to="/health" className="text-brand-700 underline">Update my needs</Link>{practices.map(p=><article className="card" key={p.title}><h2 className="section-title">{p.title}</h2><p className="mt-1 text-xs font-semibold text-brand-700">{p.why}</p><p className="mt-3 text-sm leading-relaxed">{p.steps}</p><a className="mt-3 block text-xs text-brand-700 underline" href={p.source} target="_blank" rel="noreferrer">Evidence and safety: NIH</a></article>)}</div></div>;
}
