import {createRecordId} from "../lib/recordId";
import {useState} from "react";
import Header from "../components/Header";
import {useMeasurements} from "../hooks/useWellness";
import {validMeasurement,downloadFile,type Measurement} from "../lib/wellness";
function localTime(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export default function TrackingPage(){
 const [records,save]=useMeasurements();const [kind,setKind]=useState<Measurement["kind"]>("weight");const [unit,setUnit]=useState("kg");const [date,setDate]=useState(localTime);const [value,setValue]=useState("");const [second,setSecond]=useState("");const [note,setNote]=useState("");const [message,setMessage]=useState("");const [deleting,setDeleting]=useState<string|null>(null);
 const [showEntry,setShowEntry]=useState(records.length===0);
 const filtered=records.filter(m=>m.kind===kind && (kind!=="weight" || m.unit===unit)).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));const first=filtered[0],last=filtered[filtered.length-1];
 const points=filtered.slice(-30);const min=Math.min(...points.map(m=>m.value)),max=Math.max(...points.map(m=>m.value));const t0=points[0]?Date.parse(points[0].date):0,t1=points.length?Date.parse(points[points.length-1].date):0;
 const y=(v:number)=>100-(v-min)/Math.max(max-min,1)*80;
 const csv=()=>downloadFile("moodmeal-health.csv",["date,metric,value,diastolic,unit",...records.map(m=>[m.date,m.kind,m.value,m.second??"",m.unit].join(","))].join("\r\n"),"text/csv");
 return <div className="mm-soft-bg flex h-full flex-1 flex-col"><Header title="Health trends" subtitle="Record changes, without judging them"/><div className="screen-scroll space-y-4 px-4 pt-4">
<div className="card space-y-3"> <label className="block">Measurement<select className="well-input" value={kind} onChange={(e: {target: {value: string}})=>{setKind(e.target.value as Measurement["kind"]);setValue("");setSecond("");}}><option value="weight">Weight</option><option value="blood-pressure">Blood pressure</option><option value="pulse">Pulse</option></select></label>
 {kind==="weight"&&<label className="block">Weight unit<select className="well-input" value={unit} onChange={(e: {target: {value: string}})=>setUnit(e.target.value)}><option value="kg">kg</option><option value="lb">lb</option></select></label>}
<button className="well-primary w-full" onClick={()=>{setMessage("");setShowEntry(!showEntry);}}>{showEntry?"Close entry form":"+ Add a reading"}</button></div>
 {message && <p role="status" className="rounded-xl bg-white p-3 text-sm text-brand-700">{message}</p>}
 {showEntry &&  <form className="card space-y-3" onSubmit={e=>{e.preventDefault();if(!Number.isFinite(Date.parse(date))){setMessage("Choose a valid date and time.");return;}const m:Measurement={id:createRecordId(),kind,date:new Date(date).toISOString(),value:Number(value),second:kind==="blood-pressure"?Number(second):undefined,unit:kind==="weight"?unit:kind==="pulse"?"bpm":"mmHg",note:note.trim()};if(!validMeasurement(m)){setMessage("Check the date and values. Use a past or current time and valid units; systolic must exceed diastolic.");return;}if(!save([...records,m]))return;setValue("");setSecond("");setNote("");setShowEntry(false);setMessage("Reading saved. Your trend has been updated.");}}>
 <label className="block">Date and time<input className="well-input" type="datetime-local" required max={localTime()} value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label>
 <label className="block">{kind==="blood-pressure"?"Systolic (mmHg)":kind==="pulse"?"Pulse (bpm)":`Weight (${unit})`}<input className="well-input" inputMode="decimal" type="number" step={kind==="weight"?"0.1":"1"} required value={value} onChange={e=>setValue(e.target.value)}/></label>
 {kind==="blood-pressure"&&<label className="block">Diastolic (mmHg)<input className="well-input" type="number" step="1" required value={second} onChange={e=>setSecond(e.target.value)}/></label>}
 <label className="block">Notes (optional)<input className="well-input" maxLength={300} value={note} onChange={e=>setNote(e.target.value)} /></label><button className="well-primary" type="submit">Save measurement</button></form>}
 <section className="card"><p className="mb-1 text-xs font-semibold uppercase tracking-wide text-brand-600">{filtered.length} {filtered.length===1?"reading":"readings"}</p><h2 className="section-title">Your recorded trend</h2><p className="text-xs text-slate-500">{kind==="weight"?`Weight in ${unit} (units shown separately)`:kind==="pulse"?"Pulse in bpm":"Blood pressure in mmHg; chart shows systolic"}</p>{filtered.length<2?<p className="mt-3 text-sm">Add at least two readings in the same units to see a trend.</p>:<><p className="mt-3 text-sm">First: {first.value}{first.second?`/${first.second}`:""} → Latest: {last.value}{last.second?`/${last.second}`:""} {last.unit}</p><p className="text-xs">Change: {(last.value-first.value).toFixed(1)} {last.unit}{kind==="blood-pressure"?` systolic; ${((last.second??0)-(first.second??0)).toFixed(1)} mmHg diastolic`:""}</p><svg viewBox="0 0 300 125" className="mt-3 w-full" role="img" aria-label="Time-based trend of the latest 30 readings; exact values are listed below"><line x1="15" y1="105" x2="285" y2="105" stroke="#cbd5e1"/><polyline fill="none" stroke="#7c3aed" strokeWidth="3" points={points.map(m=>`${15+(Date.parse(m.date)-t0)/Math.max(t1-t0,1)*270},${y(m.value)}`).join(" ")} />{points.map(m=><circle key={m.id} cx={15+(Date.parse(m.date)-t0)/Math.max(t1-t0,1)*270} cy={y(m.value)} r="3" fill="#7c3aed"/>)}</svg><p className="text-xs">{new Date(points[0].date).toLocaleDateString()} – {new Date(points[points.length-1].date).toLocaleDateString()}</p></>}</section>
 <p className="text-xs text-slate-500">Changes are observations, not proof of improvement or a diagnosis. This app does not monitor readings for emergencies. Share concerns with your care team.</p>
 <h2 className="section-title">Reading history</h2>
 <button className="well-secondary" disabled={!records.length} onClick={csv}>Export all readings (CSV)</button>
 {filtered.slice().reverse().map(m=><article className="card text-sm" key={m.id}><p className="font-bold">{m.value}{m.second?`/${m.second}`:""} {m.unit}</p><p>{new Date(m.date).toLocaleString()}</p><p>{m.note}</p><button className="mt-2 text-brand-700 underline" onClick={()=>{if(deleting===m.id){save(records.filter(x=>x.id!==m.id));setDeleting(null);}else setDeleting(m.id);}}>{deleting===m.id?"Confirm delete reading":"Delete reading"}</button>{deleting===m.id&&<button className="ml-3" onClick={()=>setDeleting(null)}>Cancel</button>}</article>)}
 </div></div>;
}
